server:
    port: 9000

spring:
    application:
        name: gateway
    security:
        oauth2:
            client:
                registration:
                    keycloak:
                        client-id: gateway
                        client-secret: p56ucMZf5QNyRKEq7jCZtsaYTuzX08yW
                        scope: openid, profile, email
                provider:
                    keycloak:
                        issuer-uri: http://localhost:8080/realms/dev
    cloud:
        gateway:
            routes:
                - id: hello-api
                  uri: http://localhost:8081
                  predicates:
                    - Path=/hello/**
                  filters:
                    - RemoveRequestHeader=Cookie
                    - TokenRelay=